// Built-in prompt bank — life, opinion, and perspective questions.
// Kept in its own file so it's easy to add your own later: just add a string.
const PROMPTS = [
  "What does a good life look like to you?",
  "What is something you believe that most people around you don't?",
  "When do you feel most like yourself?",
  "What would you do differently if no one was watching?",
  "What does success mean to you right now, honestly?",
  "Who has shaped the way you think the most, and how?",
  "What is a fear you'd like to outgrow this year?",
  "What does 'home' mean to you?",
  "What kind of person are you trying to become?",
  "What advice would you give your younger self?",
  "What is something you've changed your mind about recently?",
  "What makes you lose track of time in a good way?",
  "How do you want to be remembered?",
  "What is a small thing that brings you joy?",
  "What does freedom mean to you?",
  "When was the last time you felt truly proud of yourself?",
  "What do you think people misunderstand about you?",
  "What is worth being patient for?",
  "What would you attempt if you knew you could not fail?",
  "What does love look like in your everyday life?",
  "What is a habit you'd like to build, and why?",
  "What is something you're grateful for that's easy to overlook?",
  "How do you decide what is right when it isn't obvious?",
  "What does growing up mean to you?",
  "What is a belief you hold that you find hard to explain?",
  "What kind of world do you hope to live in one day?",
  "What is the best decision you've ever made?",
  "What do you need more of in your life? Less of?",
  "What does it mean to live an honest life?",
  "If today were a chapter in your story, what would you title it?",
  "What's a conversation you keep replaying in your mind?",
  "What did you need to hear today?",
  "What are you holding onto that you could let go of?",
  "Who do you miss, and what would you tell them?",
  "What does rest look like for you?",
  "What is something you're proud of that no one knows about?",
  "When did you last surprise yourself?",
  "What are you curious about lately?",
  "What is a risk that turned out to be worth it?",
  "What does kindness mean to you?",
  "What season of life do you feel you're in right now?",
  "What is a story your family tells about you?",
  "What would a perfectly ordinary good day look like?",
  "What are you learning to accept about yourself?",
  "What do you wish you had more courage to do?",
  "What is something beautiful you noticed recently?",
  "Who makes you feel most understood?",
  "What is a promise you'd like to keep to yourself?",
  "What does your ideal morning feel like?",
  "What is something you've forgiven yourself for?",
  "What would you like to be doing more of a year from now?",
  "What is a question you're still trying to answer?",
  "What comforts you when things feel heavy?",
  "What have you outgrown this year?",
  "What does a meaningful friendship look like to you?",
  "What is the kindest thing someone has done for you?",
  "What do you hope stays the same, even as everything changes?",
  "What are you working toward, quietly?",
  "What would you write in a letter to yourself in ten years?",
  "When do you feel most at peace?",
];
